# Generated by Django 6.0.5 on 2026-06-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategorie/Žánr')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název vydavatele/studia')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Webová stránka')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název hry')),
                ('description', models.TextField(verbose_name='Popis hry')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Rok vydání')),
                ('categories', models.ManyToManyField(to='catalogue.category', verbose_name='Kategorie')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.publisher', verbose_name='Vydavatel')),
            ],
        ),
    ]
