# Generated by Django 6.0.5 on 2026-06-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/', verbose_name='Obrázek/Obal'),
        ),
    ]
