# Generated by Django 6.0.5 on 2026-06-03 18:44

import catalogue.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_category_name_alter_game_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Popis musí mít alespoň 10 znaků.')], verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(validators=[catalogue.models.validate_year], verbose_name='Rok vydání'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
