# Generated by Django 6.0.5 on 2026-06-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorie",
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["title"],
                "verbose_name": "Hra",
                "verbose_name_plural": "Hry",
            },
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={
                "ordering": ["name"],
                "verbose_name": "Vydavatel",
                "verbose_name_plural": "Vydavatelé",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Recenze",
                "verbose_name_plural": "Recenze",
            },
        ),
    ]
